core/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index),
    path('browsecars', views.ExternalCarListView.as_view(), name='externalcarlist'),
    path('cardetails/<int:pk>', views.ExternalCarDetailView.as_view(), name='externalcardetails'),
    path('storedetails/<int:pk>', views.ExternalStoreDetailView.as_view(), name='externalstoredetails'),
    path('stores',
        permission_required("core.view_store")
        (login_required(views.StoreListView.as_view())), name='storelist'),
    path('stores/<int:pk>',
        permission_required("core.view_store")
        (login_required(views.StoreDetailView.as_view())), name='storedetails'),
    path('stores/create',
        permission_required("core.view_store")
        (login_required(views.StoreCreateForm.as_view())), name='storecreateform'),
    path('stores/<int:pk>/edit',
        permission_required("core.view_store")
        (login_required(views.StoreUpdateForm.as_view())), name='storeupdateform'),
    path('cars',
        permission_required("core.view_car")
        (login_required(views.CarListView.as_view())), name='carlist'),
    path('cars/<int:pk>',
        permission_required("core.view_car")
        (login_required(views.CarDetailView.as_view())), name='cardetails'),
    path('cars/create',
        permission_required("Core.view_car")
        (login_required(views.CarCreateForm.as_view())), name='carcreateform'),
    path('cars/<int:pk>/edit',
        permission_required("core.view_car")
        (login_required(views.CarUpdateForm.as_view())), name='carupdateform'),
    path('customers',
        permission_required("core.view_customer")
        (login_required(views.CustomerListView.as_view())), name='customerlist'),
    path('customers/<int:pk>',
        permission_required("core.view_customer")
        (login_required(views.CustomerDetailView.as_view())), name='customerdetails'),
    path('customers/create',
        permission_required("core.view_customer")
        (login_required(views.CustomerCreateForm.as_view())), name='customercreateform'),
    path('customers/<int:pk>/edit',
        permission_required("core.view_customer")
        (login_required(views.CustomerUpdateForm.as_view())), name='customerupdateform'),
    path('transactions', views.transactionlist, name='transactionlist'),
    path('transactions/create', views.TransactionCreateForm.as_view(), name='transactioncreateform'),
    path('recommend-car', views.recommend_car, name="recommendcar"),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from enum import Enum


# List of all possible states
class State(Enum):
    QLD = "Queensland"
    NSW = "New South Wales"
    VIC = "Victoria"
    ACT = "Australian Capital Territory"
    TAS = "Tasmania"
    NT = "Northern Territory"
    SA = "South Australia"
    WA = "Western Australia"


# List of all possible occupations
class Occupation(Enum):
    LAB = "Labour"
    MAN = "Manager"
    RET = "Retiree"
    NUR = "Nurse"
    RES = "Researcher"
    OTH = "Other"


# List of all possible genders
class Gender(Enum):
    MA = "Male"
    FE = "Female"


# List of all possible transaction types
class TransactionType(Enum):
    PIC = "Pickup"
    RET = "Return"


# Represents a store in the system
class Store(models.Model):
    name = models.CharField(max_length = 50)
    address = models.CharField(max_length = 200)
    phone = models.CharField(max_length = 30)
    city = models.CharField(max_length = 200)
    state = models.CharField(
        max_length = 40,
        choices = [(item.name, item.value) for item in State]
    )
    def __str__(self):
        return self.name


# Represents a car in the system
class Car(models.Model):
    make = models.CharField(max_length = 100)
    model = models.CharField(max_length = 100)
    series = models.CharField(max_length = 100)
    series_year = models.CharField(max_length = 100)
    price = models.IntegerField()
    enginesize = models.CharField(max_length = 10)
    fuelsystem = models.CharField(max_length = 100)
    tankcapacity = models.CharField(max_length = 100)
    power = models.CharField(max_length = 10)
    seats = models.IntegerField()
    standardtransmission = models.CharField(max_length = 100)
    bodyType = models.CharField(max_length = 100)
    drive = models.CharField(max_length = 50)
    wheelbase = models.CharField(max_length = 20)
    def __str__(self):
        return self.make + ' ' + self.model + ' ' + ' ('+  self.series + '/' + self.series_year + ')'


# Represents a customer in the system
class Customer(models.Model):
    name = models.CharField(max_length = 100)
    phone = models.CharField(max_length = 30)
    address = models.CharField(max_length = 200)
    birthday = models.DateField()
    occupation = models.CharField(
        max_length = 20,
        choices = [(item.name, item.value) for item in Occupation]
    )
    gender = models.CharField(
        max_length = 10,
        choices = [(item.name, item.value) for item in Gender]
    )
    def __str__(self):
        return self.name


# Represents a transaction within the system
class Transaction(models.Model):
    class Meta:
        get_latest_by = 'time'
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    car = models.ForeignKey(Car, on_delete = models.CASCADE)
    store = models.ForeignKey(Store, on_delete = models.CASCADE)
    time = models.DateTimeField()
    type = models.CharField(
        max_length = 10,
        choices = [(item.name, item.value) for item in TransactionType],
        default = "Pickup"
    )
    def __str__(self):
        return 'Transaction ID' + str(self.id)

core/views.py
from django.core import paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import Car, Customer, Store, Transaction
from django import forms
from django.template import Template, Context
from .forms import TransactionsGetForm, CarRecommendForm, ExternalStoreSelectForm
from .helpers.recommend import apply_filters
from datetime import datetime, timedelta, time
from .helpers.transactions import create_chart, get_transactions_by_dates
from bootstrap_datepicker_plus import DatePickerInput, DateTimePickerInput


def index(request):
    """ Renders the main screen template. """
    return render(request, 'core/index.html')


class StoreListView(generic.ListView):
    """ Represents the car list view. Extends the generic list view class. """
    template_name = 'core/store_list.html'
    context_object_name = 'store_list'
    paginate_by = 10
    def get_queryset(self):
        """Returns a list of stores"""
        return Store.objects.order_by('id')


class StoreDetailView(generic.DetailView):
    """ Represents the store detail view. Extends the generic detail view class. """
    model = Store
    template_name = 'core/store_details.html'
    transactions_paginate_by = 10
    def get_context_data(self, **kwargs):
        """Povides the data (in the form of a context object) for the store details page."""
        context = super(StoreDetailView, self).get_context_data(**kwargs)
        transactions_page = self.request.GET.get("transactions_page")
        transactions = self.object.transaction_set.filter().order_by('-time')
        transactions_paginator = paginator.Paginator(transactions, self.transactions_paginate_by)
        try:
            transactions_page_obj = transactions_paginator.page(transactions_page)
        except:
            transactions_page_obj = transactions_paginator.page(1)
        context["transactions_page_obj"] = transactions_page_obj
        context["transactions_paginator"] = transactions_paginator
        return context


class ExternalCarListView(generic.ListView):
    """ Represents the external car list view. Extends the generic list view class. """
    model = Car
    template_name = 'core/external_car_list.html'
    paginate_by = 10
    def get_context_data(self, **kwargs):
        context = super(ExternalCarListView, self).get_context_data(**kwargs)
        latest_transactions = []
        for car in Car.objects.all():
            if car.transaction_set.last() is not None:
                latest_transactions.append(car.transaction_set.last())
        latest_transactions.sort(key=lambda object: object.time, reverse=True)
        cars = []
        for transaction in latest_transactions:
            cars.append(transaction.car)
        context['car_list'] = cars
        return context
            

class ExternalCarDetailView(generic.DetailView):
    """ Represents the external car details view. Extends the generic details view class. """
    model = Car
    template_name = 'core/external_car_details.html'


class ExternalStoreDetailView(generic.DetailView):
    """ Represents the external store details view. Extends the generic details view class. """
    model = Store
    template_name = 'core/external_store_details.html'
    def get_context_data(self, **kwargs):
        context = super(ExternalStoreDetailView, self).get_context_data(**kwargs)
        form = ExternalStoreSelectForm(initial={'store': context['store'].id})
        # Getting a list of all the cars last seen at this store.
        store_cars = []
        for car in Car.objects.all():
            latest_transaction = car.transaction_set.last()
            if latest_transaction is not None and latest_transaction.store.id == context['store'].id:
                store_cars.append(car)
        context['cars'] = store_cars
        context['form'] = form
        return context

    def get(self, request, *args, **kwargs):
        if (request.GET.get('store') is not None):
            return HttpResponseRedirect(request.GET.get('store'))
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class CarListView(generic.ListView):
    """ Represents the car list view. Extends the generic list view class. """
    template_name = 'core/car_list.html'
    context_object_name = 'car_list'
    paginate_by = 10
    def get_queryset(self):
        """Returns a list of cars"""
        return Car.objects.order_by('id')


class CarDetailView(generic.DetailView):
    """ Represents the car detail view. Extends the generic detail view class. """
    model = Car
    template_name = 'core/car_details.html'
    transactions_paginate_by = 10
    def get_context_data(self, **kwargs):
        """Provides the data (in the form of a context object) for the car details page."""
        context = super(CarDetailView, self).get_context_data(**kwargs)
        transactions_page = self.request.GET.get("transactions_page")
        transactions = self.object.transaction_set.filter().order_by('-time')
        transactions_paginator = paginator.Paginator(transactions, self.transactions_paginate_by)
        try:
            transactions_page_obj = transactions_paginator.page(transactions_page)
        except:
            transactions_page_obj = transactions_paginator.page(1)
        context["transactions_page_obj"] = transactions_page_obj
        context["transactions_paginator"] = transactions_paginator
        return context


class CustomerListView(generic.ListView):
    """  Represents the customer list view. Extends the generic list view class. """
    template_name = 'core/customer_list.html'
    context_object_name = 'customer_list'
    paginate_by = 10
    def get_queryset(self):
        """Returns a list of customers"""
        return Customer.objects.order_by('id')


class CustomerDetailView(generic.DetailView):
    """ Represents the customer detail view. Extends the generic detail view class. """
    model = Customer
    template_name = 'core/customer_details.html'
    transactions_paginate_by = 10
    def get_context_data(self, **kwargs):
        """Provides the data (in the form of a context object) for the customer details page."""
        context = super(CustomerDetailView, self).get_context_data(**kwargs)
        transactions_page = self.request.GET.get("transactions_page")
        transactions = self.object.transaction_set.filter().order_by('-time')
        transactions_paginator = paginator.Paginator(transactions, self.transactions_paginate_by)
        try:
            transactions_page_obj = transactions_paginator.page(transactions_page)
        except:
            transactions_page_obj = transactions_paginator.page(1)
        context["transactions_page_obj"] = transactions_page_obj
        context["transactions_paginator"] = transactions_paginator
        return context


class CustomerCreateForm(generic.edit.CreateView):
    """ Represents the customer create form view. """
    # The Generic CreateView class automatically searches for template core/customer_form
    model = Customer
    fields = ['name', 'phone', 'address', 'birthday', 'occupation', 'gender']
    success_url = '/customers?createsuccess=true'

    def get_form(self, form_class=None):
        """ Extending the generic createview get_form function to change the birthday form field widget. """
        if form_class is None: form_class = self.get_form_class()
        form = super(CustomerCreateForm, self).get_form(form_class)
        form.fields['birthday'] = forms.DateField(widget=DatePickerInput(format='%d/%m/%Y'), input_formats=['%d/%m/%Y'])
        return form


class CustomerUpdateForm(generic.edit.UpdateView):
    """ Represents the customer update form view. """
    # The Generic UpdateView class automatically searches for template core/customer_form
    model = Customer
    fields = ['name', 'phone', 'address', 'birthday', 'occupation', 'gender']
    success_url = '/customers?updatesuccess=true'

    def get_form(self, form_class=None):
        """ Extending the generic updateview get_form function to change the birthday form field widget. """
        if form_class is None: form_class = self.get_form_class()
        form = super(CustomerUpdateForm, self).get_form(form_class)
        form.fields['birthday'] = forms.DateField(widget=DatePickerInput(format='%d/%m/%Y'), input_formats=['%d/%m/%Y'])
        return form


class TransactionCreateForm(generic.edit.CreateView):
    """ Represents the transaction create form view. """
    model = Transaction
    fields = ['customer', 'car', 'store', 'time', 'type']
    success_url = '/transactions?createsuccess=true'

    def get_form(self, form_class=None):
        if form_class is None: form_class = self.get_form_class()
        form = super(TransactionCreateForm, self).get_form(form_class)
        form.fields['time'] = forms.DateTimeField(widget=DateTimePickerInput(format='%d/%m/%Y %H:%M:%S'), input_formats=['%d/%m/%Y %H:%M:%S'])
        return form


class StoreCreateForm(generic.edit.CreateView):
    """ Represents the store create form view. """
    model = Store
    fields = ['name', 'address', 'phone', 'city', 'state']
    success_url = '/stores?createsuccess=true'


class StoreUpdateForm(generic.edit.UpdateView):
    """ Represents the store update form view. """
    model = Store
    fields = ['name', 'address', 'phone', 'city', 'state']
    success_url = '/stores?updatesuccess=true'


class CarCreateForm(generic.edit.CreateView):
    """ Represents the car create form view. """
    model = Car
    fields = ['make', 'model', 'series', 'series_year', 'price', 'enginesize', 'fuelsystem', 'tankcapacity', 'power', 'seats', 'standardtransmission', 'bodyType', 'drive', 'wheelbase']
    success_url = '/cars?createsuccess=true'

templates/core/car_details.html
{% extends "../details_page.html" %}
{% block nav-cars %}<a class="nav-link active" href="/cars">Cars</a>{% endblock %}
{% block left-header %}
    <img src="/static/images/car.png" class="entity-image">
    <h4 class="entity-title pb-4">{{ car.make }} {{ car.model }} <a href="{{ car.id }}/edit"><i class="far fa-edit"></i></a></h4>
{% endblock %}
{% block left-content %}
    <div class="detail-head">Series/Year</div> <div class="detail-body">{{ car.series }}/{{ car.series_year }}</div>
    <div class="detail-head">Price</div> <div class="detail-body">${{ car.price }}</div>
    <div class="detail-head">Seats</div> <div class="detail-body">{{ car.seats }}</div>
    <div class="detail-head">Engine Size</div> <div class="detail-body">{{ car.enginesize }}</div>
    <div class="detail-head">Fuel System</div> <div class="detail-body">{{ car.fuelsystem }}</div>
    <div class="detail-head">Tank Capacity</div> <div class="detail-body">{{ car.tankcapacity }}</div>
    <div class="detail-head">Power</div> <div class="detail-body">{{ car.power }}</div>
    <div class="detail-head">Standard Transmission</div> <div class="detail-body">{{ car.standardtransmission }}</div>
    <div class="detail-head">Body Type</div> <div class="detail-body">{{ car.bodyType }}</div>
    <div class="detail-head">Drive</div> <div class="detail-body">{{ car.drive }}</div>
    <div class="detail-head">Wheel Base</div> <div class="detail-body">{{ car.wheelbase }}</div>
{% endblock %}
{% block right-content %}
    <h3>Transactions</h3>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Transaction Id</th>
                    <th>Customer</th>
                    <th>Store</th>
                    <th>Date/Time</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for transaction in transactions_page_obj.object_list %}
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td><a href="/customers/{{ transaction.customer.id }}">{{ transaction.customer.name }}</a></td>
                    <td><a href="/stores/{{ transaction.store.id }}">{{ transaction.store|stringformat:"s" }}</a></td>
                    <td>{{ transaction.time }}</td>
                    <td>{{ transaction.get_type_display }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "../transaction_sub_pagination.html" %}
{% endblock %}

templates/core/car_list.html
{% extends "../base.html" %}
{% block nav-cars %}<a class="nav-link active" href="/cars">Cars</a>{% endblock %}

{% block content %}
<div class="px-2 d-flex mt-auto align-items-center justify-content-between">
    <h3 class="pl-4 pt-2">Cars</h3>
    <a href="/cars/create"><button class="btn btn-primary mr-3" style="height: 38px;">Create</button></a>
</div>
    {% if car_list %}
        <div class="table-responsive pl-4 pr-4 pt-1">
            <table class="table">
                <thead>
                    <tr>
                        <th>Car Id</th>
                        <th>Make</th>
                        <th>Model</th>
                        <th>Series</th>
                        <th>Year</th>
                        <th>Price</th>
                        <th>Seats</th>
                        <th>Body Type</th>
                        <th>Last Recorded Location</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for car in car_list %}
                    <tr>
                        <td><a href="cars/{{ car.id }}">{{ car.id }}</a></td>
                        <td>{{ car.make }}</td>
                        <td>{{ car.model }}</td>
                        <td>{{ car.series }}</td>
                        <td>{{ car.series_year }}</td>
                        <td>{{ car.price }}</td>
                        <td>{{ car.seats }}</td>
                        <td>{{ car.bodyType }}</td>
                        <td>
                            {% if car.transaction_set.last.type == 'PIC' %}
                                <span class="text-danger">WITH CUSTOMER</span>
                            {% elif car.transaction_set.last.type == 'RET' %}
                                <a href="/stores/{{car.transaction_set.last.store.id}}">{{ car.transaction_set.last.store.name }}</a>
                            {% else %}
                                N/A
                            {% endif %}
                        </td>
                        <td><a href="cars/{{ car.id }}/edit"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "../pagination.html" %}
    {% else %}
        <p>No cars are available.</p>
    {% endif %}
{% endblock %}

templates/core/customer_details.html
{% extends "../details_page.html" %}
{% block nav-customers %}<a class="nav-link active" href="/customers">Customers</a>{% endblock %}
{% block left-header %}
    <img src="/static/images/customer.png" class="entity-image">
    <h4 class="entity-title pb-4">{{ customer.name }} <a href="{{ customer.id }}/edit"><i class="far fa-edit"></i></a></h4>
{% endblock %}
{% block left-content %}
    <div class="detail-head">Phone Number</div> <div class="detail-body">{{ customer.phone }}</div>
    <div class="detail-head">Address</div> <div class="detail-body">{{ customer.address }}</div>
    <div class="detail-head">Birthday</div> <div class="detail-body">{{ customer.birthday }}</div>
    <div class="detail-head">Occupation</div> <div class="detail-body">{{ customer.get_occupation_display }}</div>
    <div class="detail-head">Gender</div> <div class="detail-body">{{ customer.get_gender_display }}</div>
{% endblock %}
{% block right-content %}
    <h3>Transactions</h3>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Transaction Id</th>
                    <th>Car</th>
                    <th>Store</th>
                    <th>Date/Time</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for transaction in transactions_page_obj.object_list %}
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td><a href="/cars/{{ transaction.car.id }}">{{ transaction.car.make }} {{ transaction.car.model }}</a></td>
                    <td><a href="/stores/{{ transaction.store.id }}">{{ transaction.store|stringformat:"s" }}</a></td>
                    <td>{{ transaction.time }}</td>
                    <td>{{ transaction.get_type_display }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "../transaction_sub_pagination.html" %}
{% endblock %}

templates/core/customer_list.html
{% extends "../base.html" %}
{% block nav-customers %}<a class="nav-link active" href="/customers">Customers</a>{% endblock %}

{% block content %}
<div class="px-2 d-flex mt-auto align-items-center justify-content-between">
    <h3 class="pl-4 pt-2">Customers</h3>
    <a href="/customers/create"><button class="btn btn-primary mr-3" style="height: 38px;">Create</button></a>
</div>
    {% if customer_list %}
        <div class="table-responsive pl-4 pr-4 pt-1">
            <table class="table">
                <thead>
                    <tr>
                        <th>Customer Id</th>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>Birthday</th>
                        <th>Occupation</th>
                        <th>Gender</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for customer in customer_list %}
                    <tr>
                        <td><a href="customers/{{ customer.id }}">{{ customer.id }}</a></td>
                        <td><a href="customers/{{ customer.id }}">{{ customer.name }}</a></td>
                        <td>{{ customer.phone }}</td>
                        <td>{{ customer.address }}</td>
                        <td>{{ customer.birthday }}</td>
                        <td>{{ customer.get_occupation_display }}</td>
                        <td>{{ customer.get_gender_display }}</td>
                        <td><a href="customers/{{ customer.id }}/edit"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "../pagination.html" %}
    {% else %}
        <p>No customers are available.</p>
    {% endif %}
{% endblock %}

templates/core/store_list.html
{% extends "../base.html" %}
{% block nav-stores %}<a class="nav-link active" href="/stores">Stores</a>{% endblock %}

{% block content %}
<div class="px-2 d-flex mt-auto align-items-center justify-content-between">
    <h3 class="pl-4 pt-2">Stores</h3>
    <a href="/stores/create"><button class="btn btn-primary mr-3" style="height: 38px;">Create</button></a>
</div>
    {% if store_list %}
        <div class="table-responsive pl-4 pr-4 pt-1">
            <table class="table">
                <thead>
                    <tr>
                        <th>Store Id</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>State</th>
                        <th>Phone</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for store in store_list %}
                    <tr>
                        <td>{{ store.id }}</td>
                        <td><a href="stores/{{ store.id }}">{{ store.name }}</a></td>
                        <td>{{ store.address }}</td>
                        <td>{{ store.city }}</td>
                        <td>{{ store.get_state_display }}</td>
                        <td>{{ store.phone }}</td>
                        <td><a href="stores/{{ store.id }}/edit"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "../pagination.html" %}
    {% else %}
        <p>No stores are available.</p>
    {% endif %}
{% endblock %}

templates/core/transaction_form.html
{% extends "../base.html" %}
{% load includecss %}
{% block nav-transactions %}<a class="nav-link active" href="/transactions">Transactions</a>{% endblock %}

{% block content %}
<div class="mx-4">
    <div style="max-width: 900px;" class="mx-auto">
        <h1 class="pt-3">Create Transaction</h1>
        {{ form.media }}
        <form action="" method="post">
            {% csrf_token %}
            <div class="pt-2 pb-4">
                <div class="py-2">
                    {% csrf_token %}
                    {{ form.customer.errors }}
                    <label for="{{ form.customer.id_for_label }}">Customer</label>
                    {{ form.customer|includecss:"form-control" }}
                </div>
                <div class="py-2">
                    {{ form.car.errors }}
                    <label for="{{ form.car.id_for_label }}">Car</label>
                    {{ form.car|includecss:"form-control" }}
                </div>
                <div class="py-2">
                    {{ form.store.errors }}
                    <label for="{{ form.store.id_for_label }}">Store</label>
                    {{ form.store|includecss:"form-control" }}
                </div>
                <div class="py-2">
                    {{ form.time.errors }}
                    <label for="{{ form.time.id_for_label }}">Time</label>
                    {{ form.time }}
                </div>
                <div class="py-2">
                    {{ form.type.errors }}
                    <label for="{{ form.type.id_for_label }}">Type</label>
                    {{ form.type|includecss:"form-control" }}
                </div>
                <div class="p-2">
                    <input type="submit" value="Submit" class="btn btn-primary pl-auto" style="height: 38px; float: right;">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/core/transaction_list.html
{% extends "../base.html" %}
{% block nav-transactions %}<a class="nav-link active" href="/transactions">Transactions</a>{% endblock %}

{% block content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>
{{ form.media }}
<div class="px-2 d-flex mt-auto align-items-center justify-content-between">
    <h3 class="pl-4 pt-2">Transactions</h3>
    <a href="transactions/create"><button class="btn btn-primary mr-3" style="height: 38px;">Create</button></a>
</div>
<div class="transaction-content pl-4">
    <div class="transaction-criteria">
        <form action="/transactions" autocomplete="off" method="get">
            <div class="d-flex pt-2 pb-4">
                <div class="px-2">
                    {% csrf_token %}
                    {{ form.start_date.errors }}
                    <label for="{{ form.start_date.id_for_label }}">Start Date:</label>
                    {{ form.start_date }}
                </div>
                <div class="px-2">
                    {{ form.end_date.errors }}
                    <label for="{{ form.end_date.id_for_label }}">End Date:</label>
                    {{ form.end_date }}
                </div>
                <div class="px-2">
                    {{ form.media_type.errors }}
                    <label for="{{ form.media_type.id_for_label }}">Media Type:</label>
                    {{ form.media_type }}
                </div>
                <div class="px-2 d-flex mt-auto">
                    <input type="submit" value="Submit" class="btn btn-primary" style="height: 38px;">
                </div>
            </div>
        </form>
    </div>
</div>
{% if transaction_list %}
    {% if media_type == 'table' %}
        <div class="table-responsive pl-4 pr-4 pt-1">
            <table class="table">
                <thead>
                    <tr>
                        <th>Transaction Id</th>
                        <th>Store</th>
                        <th>Customer</th>
                        <th>Car</th>
                        <th>Date/Time</th>
                        <th>Type</th>
                    </tr>
                </thead>
                <tbody>
                {% for transaction in page_obj.object_list %}
                    <tr>
                        <td>{{ transaction.id }}</td>
                        <td><a href="/store/{{ transaction.store.id }}">{{ transaction.store.name }}</a></td>
                        <td><a href="/customers/{{ transaction.customer.id }}">{{ transaction.customer.name }}</a></td>
                        <td><a href="/cars/{{ transaction.car.id }}">{{ transaction.car|stringformat:"s" }}</a></td>
                        <td>{{ transaction.time }}</td>
                        <td>{{ transaction.get_type_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "../pagination.html" %}
    {% elif media_type == 'line' or media_type == 'pie' or media_type == 'bar' %}
        {{ chart.as_html }}
    {% endif %}
{% else %}
    <p class="pl-5">No transactions for this time period.</p>
{% endif %}
{% endblock %}